#include <unity.h>

#ifndef I2S_NUM_1
#define I2S_NUM_1 1
#endif

#ifndef I2S_BITS_PER_SAMPLE_32BIT
#define I2S_BITS_PER_SAMPLE_32BIT 32
#endif

#ifndef I2S_CHANNEL_FMT_RIGHT_LEFT
#define I2S_CHANNEL_FMT_RIGHT_LEFT 0
#endif

#ifndef I2S_COMM_FORMAT_STAND_I2S
#define I2S_COMM_FORMAT_STAND_I2S 1
#endif

#include "core/mic/mic_config.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_mic_brightness_bounds(void)
{
  TEST_ASSERT_GREATER_OR_EQUAL_UINT16(0, MIC_MIN_BRIGHTNESS);
  TEST_ASSERT_LESS_OR_EQUAL_UINT16(255, MIC_MIN_BRIGHTNESS);
  TEST_ASSERT_GREATER_OR_EQUAL_UINT16(MIC_MIN_BRIGHTNESS + 1, MIC_MAX_BRIGHTNESS);
  TEST_ASSERT_LESS_OR_EQUAL_UINT16(255, MIC_MAX_BRIGHTNESS);
}

void test_mic_alpha_ranges(void)
{
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_DC_BLOCK_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_DC_BLOCK_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_SIGNAL_ATTACK_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_SIGNAL_ATTACK_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_SIGNAL_RELEASE_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_SIGNAL_RELEASE_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_NOISE_FLOOR_RISE_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_NOISE_FLOOR_RISE_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_NOISE_FLOOR_FALL_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_NOISE_FLOOR_FALL_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_PEAK_REF_ATTACK_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_PEAK_REF_ATTACK_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_PEAK_REF_RELEASE_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_PEAK_REF_RELEASE_ALPHA);
}

void test_mic_level_bounds(void)
{
  TEST_ASSERT_GREATER_THAN_FLOAT(MIC_NOISE_FLOOR_MIN, MIC_NOISE_FLOOR_INIT);
  TEST_ASSERT_GREATER_THAN_FLOAT(MIC_NOISE_FLOOR_INIT, MIC_NOISE_FLOOR_MAX);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_NOISE_FLOOR_MIN);
  TEST_ASSERT_GREATER_THAN_FLOAT(MIC_PEAK_REF_MIN, MIC_PEAK_REF_MAX);
  TEST_ASSERT_GREATER_OR_EQUAL_FLOAT(MIC_PEAK_REF_MIN, MIC_PEAK_REF_INIT);
}

void test_mic_threshold_ratios(void)
{
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_NOISE_FLOOR_GATE_BAND);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_NOISE_GATE_MARGIN);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_MOUTH_OPEN_THRESHOLD);
  TEST_ASSERT_GREATER_THAN_FLOAT(MIC_MOUTH_CLOSE_THRESHOLD, MIC_MOUTH_OPEN_THRESHOLD);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_MOUTH_CLOSE_THRESHOLD);
}

void test_mic_timing_ranges(void)
{
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_MOUTH_OPEN_HOLD_MS);
  TEST_ASSERT_GREATER_OR_EQUAL_INT(0, MIC_POWER_UP_DELAY_MS);
}

void test_mic_sampling_ranges(void)
{
  TEST_ASSERT_GREATER_OR_EQUAL_INT(16000, MIC_SAMPLE_RATE);
  TEST_ASSERT_LESS_OR_EQUAL_INT(64000, MIC_SAMPLE_RATE);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_DMA_BUF_COUNT);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_DMA_BUF_LEN);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_READ_TIMEOUT_MS);
  TEST_ASSERT_GREATER_OR_EQUAL_INT(0, MIC_SAMPLE_SHIFT);
  TEST_ASSERT_LESS_OR_EQUAL_INT(31, MIC_SAMPLE_SHIFT);
  TEST_ASSERT_EQUAL_INT(I2S_CHANNEL_FMT_RIGHT_LEFT, MIC_CHANNEL_FORMAT);
  TEST_ASSERT_EQUAL_INT(2, MIC_SLOT_COUNT);
}

void setup()
{
  UNITY_BEGIN();
  RUN_TEST(test_mic_brightness_bounds);
  RUN_TEST(test_mic_alpha_ranges);
  RUN_TEST(test_mic_level_bounds);
  RUN_TEST(test_mic_threshold_ratios);
  RUN_TEST(test_mic_timing_ranges);
  RUN_TEST(test_mic_sampling_ranges);
  UNITY_END();
}

int main()
{
  setup();
  return 0;
}

void loop()
{
  // Unity tests run once
}
