#include <unity.h>

#ifndef I2S_NUM_1
#define I2S_NUM_1 1
#endif

#ifndef I2S_BITS_PER_SAMPLE_32BIT
#define I2S_BITS_PER_SAMPLE_32BIT 32
#endif

#ifndef I2S_CHANNEL_FMT_ONLY_LEFT
#define I2S_CHANNEL_FMT_ONLY_LEFT 1
#endif

#ifndef I2S_COMM_FORMAT_STAND_I2S
#define I2S_COMM_FORMAT_STAND_I2S 1
#endif

#include "core/mic/mic_config.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_mic_brightness_bounds(void)
{
  TEST_ASSERT_GREATER_OR_EQUAL_UINT16(0, MIC_MIN_BRIGHTNESS);
  TEST_ASSERT_LESS_OR_EQUAL_UINT16(255, MIC_MIN_BRIGHTNESS);
  TEST_ASSERT_GREATER_OR_EQUAL_UINT16(MIC_MIN_BRIGHTNESS + 1, MIC_MAX_BRIGHTNESS);
  TEST_ASSERT_LESS_OR_EQUAL_UINT16(255, MIC_MAX_BRIGHTNESS);
}

void test_mic_alpha_ranges(void)
{
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_BRIGHTNESS_ATTACK_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_BRIGHTNESS_ATTACK_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_BRIGHTNESS_RELEASE_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_BRIGHTNESS_RELEASE_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_AMBIENT_EMA_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_AMBIENT_EMA_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_AMBIENT_FALL_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_AMBIENT_FALL_ALPHA);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_SIGNAL_EMA_ALPHA);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_SIGNAL_EMA_ALPHA);
}

void test_mic_ambient_bounds(void)
{
  TEST_ASSERT_GREATER_THAN_FLOAT(MIC_MIN_AMBIENT_LEVEL, MIC_MAX_AMBIENT_LEVEL);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_MIN_AMBIENT_LEVEL);
}

void test_mic_threshold_ratios(void)
{
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_SENSITIVITY_OFFSET_ABOVE_AMBIENT);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_CLOSE_HYSTERESIS_RATIO);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_CLOSE_HYSTERESIS_RATIO);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_AMBIENT_UPDATE_BAND);
  TEST_ASSERT_LESS_THAN_FLOAT(1.0f, MIC_AMBIENT_UPDATE_BAND);
  TEST_ASSERT_GREATER_THAN_FLOAT(1.0f, MIC_IMPULSE_PEAK_RATIO);
  TEST_ASSERT_GREATER_THAN_FLOAT(0.0f, MIC_IMPULSE_MAX_AVG_RATIO);
}

void test_mic_timing_ranges(void)
{
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_MOUTH_OPEN_HOLD_MS);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_MIN_OPEN_MS);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_IMPULSE_HOLDOFF_MS);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_AMBIENT_UPDATE_QUIET_PERIOD_MS);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_AMBIENT_SILENCE_UPDATE_MS);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_OPEN_REBASE_MS);
}

void test_mic_sampling_ranges(void)
{
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_SAMPLE_RATE);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_DMA_BUF_COUNT);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_DMA_BUF_LEN);
  TEST_ASSERT_GREATER_THAN_INT(0, MIC_READ_TIMEOUT_MS);
  TEST_ASSERT_GREATER_OR_EQUAL_INT(0, MIC_SAMPLE_SHIFT);
  TEST_ASSERT_LESS_OR_EQUAL_INT(31, MIC_SAMPLE_SHIFT);
}

void setup()
{
  UNITY_BEGIN();
  RUN_TEST(test_mic_brightness_bounds);
  RUN_TEST(test_mic_alpha_ranges);
  RUN_TEST(test_mic_ambient_bounds);
  RUN_TEST(test_mic_threshold_ratios);
  RUN_TEST(test_mic_timing_ranges);
  RUN_TEST(test_mic_sampling_ranges);
  UNITY_END();
}

int main()
{
  setup();
  return 0;
}

void loop()
{
  // Unity tests run once
}
